"""
Esmerald settings for teste project.

Generated by 'esmerald createproject' using Esmerald 3.7.7.
"""

from typing import Optional

from esmerald.conf.enums import EnvironmentType
from esmerald.conf.global_settings import EsmeraldAPISettings
from lilya.environments import EnvironLoader
from lilya.middleware import DefineMiddleware
from lilya.middleware.sessions import SessionMiddleware

loader: EnvironLoader = EnvironLoader()


class AppSettings(EsmeraldAPISettings):
    app_name: str = "My application in production mode."
    title: str = "My teste"
    environment: Optional[str] = EnvironmentType.PRODUCTION
    secret_key: str = "esmerald-insecure-82z0fozzqbqt8&amp;y&amp;x8@_a$^yb)3$%!iwezrwbua8ps1c_h1&amp;h4"

    @property
    def middleware(self):
        return [
            DefineMiddleware(SessionMiddleware, secret_key=self.secret_key),
        ]
