import base64
import binascii
import zlib
from typing import Any, cast

import redis.asyncio as redis

from asyncmq.stores.base import BaseJobStore

COMPRESSED_PAYLOAD_PREFIX = "asyncmq:zlib-json:v1:"
PAYLOAD_SPLIT_MIN_BYTES = 64 * 1024
PAYLOAD_FIELDS = ("args", "kwargs")


class RedisJobStore(BaseJobStore):
    """
    A concrete implementation of `BaseJobStore` using Redis as the backend
    for storing and retrieving job data.

    Job data is stored as JSON strings in Redis keys, and the IDs of jobs
    belonging to a queue are tracked in a Redis Set.
    """

    def __init__(self, redis_url: str | None = None, *, redis_client: redis.Redis | None = None) -> None:
        """
        Initializes the RedisJobStore by establishing a connection to Redis.

        Args:
            redis_url: The connection URL for the Redis instance. If None,
                       a client must be injected via `redis_client`.
            redis_client: An existing Redis client instance for custom usage.
        """
        if redis_client is not None:
            self.redis: redis.Redis = redis_client
        elif redis_url:
            self.redis: redis.Redis = redis.from_url(redis_url, decode_responses=True)  # type: ignore
        else:
            self.redis = None  # to be set externally

    def _key(self, queue_name: str, job_id: str) -> str:
        """
        Generates the Redis key string used to store the data for a specific job.

        The key format is typically `jobs:{queue_name}:{job_id}`.

        Args:
            queue_name: The name of the queue the job belongs to.
            job_id: The unique identifier of the job.

        Returns:
            The formatted Redis key string.
        """
        # Return the formatted Redis key for a job.
        return f"jobs:{queue_name}:{job_id}"

    def _set_key(self, queue_name: str) -> str:
        """
        Generates the Redis key string used for the Set that stores the IDs
        of all jobs belonging to a specific queue.

        The key format is typically `jobs:{queue_name}:ids`.

        Args:
            queue_name: The name of the queue.

        Returns:
            The formatted Redis key string for the Set.
        """
        # Return the formatted Redis key for the set of job IDs for a queue.
        return f"jobs:{queue_name}:ids"

    def _payload_key(self, queue_name: str, job_id: str) -> str:
        return f"{self._key(queue_name, job_id)}:payload"

    def _encode_payload_text(self, payload_json: str) -> str:
        raw = payload_json.encode("utf-8")
        compressed = zlib.compress(raw)
        encoded = base64.b64encode(compressed).decode("ascii")
        candidate = f"{COMPRESSED_PAYLOAD_PREFIX}{encoded}"
        return candidate if len(candidate.encode("utf-8")) < len(raw) else payload_json

    def _decode_payload_text(self, payload_text: str) -> str:
        if not payload_text.startswith(COMPRESSED_PAYLOAD_PREFIX):
            return payload_text
        encoded = payload_text[len(COMPRESSED_PAYLOAD_PREFIX) :]
        try:
            return zlib.decompress(base64.b64decode(encoded.encode("ascii"), validate=True)).decode("utf-8")
        except (binascii.Error, UnicodeDecodeError, zlib.error) as exc:
            raise ValueError("Invalid compressed Redis job payload") from exc

    def encode_for_storage(self, data: dict[str, Any]) -> tuple[str, str | None]:
        job_data_json: str = self._json_serializer.to_json(data)
        payload_fields = {field: data[field] for field in PAYLOAD_FIELDS if field in data}
        if len(job_data_json.encode("utf-8")) < PAYLOAD_SPLIT_MIN_BYTES or not payload_fields:
            return job_data_json, None

        metadata = {key: value for key, value in data.items() if key not in PAYLOAD_FIELDS}
        payload_json = self._json_serializer.to_json(payload_fields)
        return self._json_serializer.to_json(metadata), self._encode_payload_text(payload_json)

    def decode_from_storage(self, metadata_text: str, payload_text: str | None = None) -> dict[str, Any]:
        data = cast(dict[str, Any], self._json_serializer.to_dict(metadata_text))
        if payload_text is None:
            return data
        payload_fields = cast(dict[str, Any], self._json_serializer.to_dict(self._decode_payload_text(payload_text)))
        return {**data, **payload_fields}

    async def save(self, queue_name: str, job_id: str, data: dict[str, Any]) -> None:
        """
        Asynchronously saves the data for a specific job in Redis.

        The job data dictionary is serialized to a JSON string and stored
        in a Redis key generated by `_key`. The job ID is also added to
        the Redis Set tracked by `_set_key` for the given queue.

        Args:
            queue_name: The name of the queue the job belongs to.
            job_id: The unique identifier of the job.
            data: The dictionary containing the job's data to be saved.
        """
        job_data_json, payload_text = self.encode_for_storage(data)
        pipe = self.redis.pipeline(transaction=False)
        pipe.set(self._key(queue_name, job_id), job_data_json)
        if payload_text is None:
            pipe.delete(self._payload_key(queue_name, job_id))
        else:
            pipe.set(self._payload_key(queue_name, job_id), payload_text)
        pipe.sadd(self._set_key(queue_name), job_id)
        await pipe.execute()

    async def load(self, queue_name: str, job_id: str) -> dict[str, Any] | None:
        """
        Asynchronously loads the data for a specific job from Redis by its ID.

        Retrieves the JSON string stored at the job's key, parses it into
        a dictionary, and returns it.

        Args:
            queue_name: The name of the queue the job belongs to.
            job_id: The unique identifier of the job.

        Returns:
            A dictionary containing the job's data if the key exists and
            contains valid JSON, otherwise None.
        """
        # Retrieve the raw JSON string from Redis using the job's key.
        raw: str | bytes | None = await self.redis.get(self._key(queue_name, job_id))
        if raw is None:
            return None
        payload_raw: str | bytes | None = await self.redis.get(self._payload_key(queue_name, job_id))
        metadata_text = raw.decode("utf-8") if isinstance(raw, bytes) else raw
        payload_text = payload_raw.decode("utf-8") if isinstance(payload_raw, bytes) else payload_raw
        return self.decode_from_storage(metadata_text, payload_text)

    async def delete(self, queue_name: str, job_id: str) -> None:
        """
        Asynchronously deletes the data for a specific job from Redis.

        Removes the Redis key storing the job data and removes the job ID
        from the Set of job IDs for the queue.

        Args:
            queue_name: The name of the queue the job belongs to.
            job_id: The unique identifier of the job.
        """
        # Delete the Redis key storing the job data.
        await self.redis.delete(self._key(queue_name, job_id), self._payload_key(queue_name, job_id))
        # Remove the job ID from the set of job IDs for this queue.
        await self.redis.srem(self._set_key(queue_name), job_id)

    async def all_jobs(self, queue_name: str) -> list[dict[str, Any]]:
        """
        Asynchronously retrieves data for all jobs associated with a specific
        queue by fetching all IDs from the queue's Set and loading each job
        individually.

        Args:
            queue_name: The name of the queue.

        Returns:
            A list of dictionaries, where each dictionary is the data for a job
            in the specified queue. Jobs that cannot be loaded (e.g., key deleted
            between fetching ID and loading) are skipped.
        """
        # Get all job IDs from the set for the given queue.
        ids: list[str] = await self.redis.smembers(self._set_key(queue_name))
        jobs_data: list[dict[str, Any]] = [
            # Load each job by its ID and add it to the list if loading is successful.
            job
            for job_id in ids
            if job_id and (job := await self.load(queue_name, job_id)) is not None
        ]
        # Return the list of loaded job data dictionaries.
        return jobs_data

    async def jobs_by_status(self, queue_name: str, status: str) -> list[dict[str, Any]]:
        """
        Asynchronously retrieves data for jobs in a specific queue that are
        currently in a given status by loading all jobs and filtering in memory.

        Note: This implementation is inefficient for large queues as it loads
        all jobs first. A more scalable backend would use Redis sorted sets
        or other structures to track jobs by status natively.

        Args:
            queue_name: The name of the queue.
            status: The status of the jobs to retrieve (e.g., "waiting", "active").

        Returns:
            A list of dictionaries, where each dictionary contains the data
            for a job matching the criteria.
        """
        # Load all jobs for the specified queue.
        all_jobs: list[dict[str, Any]] = await self.all_jobs(queue_name)
        # Filter the list of jobs to include only those matching the specified status.
        filtered_jobs: list[dict[str, Any]] = [job for job in all_jobs if job and job.get("status") == status]
        # Return the filtered list of jobs.
        return filtered_jobs

    async def list_queues(self) -> list[str]:
        """
        Return queue names that have metadata entries in this Redis store.
        """
        queues: set[str] = set()
        async for raw_key in self.redis.scan_iter(match="jobs:*:ids"):
            key = raw_key.decode() if isinstance(raw_key, (bytes, bytearray)) else raw_key
            if isinstance(key, str) and key.startswith("jobs:") and key.endswith(":ids"):
                queues.add(key[len("jobs:") : -len(":ids")])
        return sorted(queues)

    async def create_lock(self, key: str, ttl: int) -> redis.lock.Lock:
        """
        Create a Redis-backed distributed lock for metadata coordination.

        Args:
            key: The logical lock identifier.
            ttl: The lock timeout in seconds.

        Returns:
            A Redis lock instance.
        """
        return self.redis.lock(key, timeout=ttl)
