#!/usr/bin/env python
"""
Generated by 'esmerald createproject' using Esmerald 3.7.7.
"""

import os
import sys
from contextlib import asynccontextmanager
from typing import Any

from esmerald import Esmerald, Include, settings


def build_path():
    """
    Builds the path of the project and project root.
    """
    SITE_ROOT = os.path.dirname(os.path.realpath(__file__))

    if SITE_ROOT not in sys.path:
        sys.path.append(SITE_ROOT)
        sys.path.append(os.path.join(SITE_ROOT, "apps"))


@asynccontextmanager
async def lifespan(app: Esmerald) -> Any:
    """
    This is optional. The function is only used for organisation purposes.
    """
    registry = settings.registry
    async with registry:
        yield


def get_application():
    """
    This is optional. The function is only used for organisation purposes.
    """
    build_path()
    from asyncmq.contrib.dashboard.application import dashboard

    app = Esmerald(
        routes=[
            Include("/", app=dashboard),
        ],
    )
    return app


app = get_application()
