"""
Esmerald settings for teste project.

Generated by 'esmerald createproject' using Esmerald 3.7.7.
"""

from typing import Optional

from esmerald.conf.enums import EnvironmentType

from ..settings import AppSettings


class DevelopmentAppSettings(AppSettings):
    debug: bool = True
    app_name: str = "My application in development mode."
    title: str = "My teste"
    environment: Optional[str] = EnvironmentType.DEVELOPMENT
